// Generated by Claude.
package auth

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	cip "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
)

func Authenticate(ctx context.Context, region, userPoolID, clientID, username, password string) (string, error) {
	cfg, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion(region))
	if err != nil {
		return "", fmt.Errorf("loading AWS config: %w", err)
	}

	client := cip.NewFromConfig(cfg)

	output, err := client.InitiateAuth(ctx, &cip.InitiateAuthInput{
		AuthFlow: types.AuthFlowTypeUserPasswordAuth,
		ClientId: aws.String(clientID),
		AuthParameters: map[string]string{
			"USERNAME": username,
			"PASSWORD": password,
		},
	})
	if err != nil {
		return "", fmt.Errorf("authenticating: %w", err)
	}

	if output.AuthenticationResult == nil || output.AuthenticationResult.IdToken == nil {
		return "", fmt.Errorf("authentication succeeded but no ID token returned")
	}

	return *output.AuthenticationResult.IdToken, nil
}
