// Generated by Claude.
// Cognito client for direct AWS SDK access to user management operations.
// Uses IAM credentials (env vars, AWS profile, or instance role) instead of Cognito user auth.
package cognito

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
)

type User struct {
	ID        string // custom:Id attribute (app user ID)
	Username  string // raw Cognito username (e.g. "google_<sub>" for federated); used for admin operations
	Name      string // human-readable: name attribute, else email, else username
	Email     string // email attribute (may be empty)
	Approved  bool
	CreatedAt time.Time
}

type Client struct {
	client     *cognitoidentityprovider.Client
	userPoolID string
}

// NewClient creates a Cognito client configured with AWS credentials from the environment.
func NewClient(ctx context.Context, region, userPoolID string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}

	return &Client{
		client:     cognitoidentityprovider.NewFromConfig(cfg),
		userPoolID: userPoolID,
	}, nil
}

// ListUsers retrieves all users from the Cognito user pool with pagination.
func (c *Client) ListUsers(ctx context.Context) ([]User, error) {
	var users []User
	var paginationToken *string

	for {
		resp, err := c.client.ListUsers(ctx, &cognitoidentityprovider.ListUsersInput{
			UserPoolId:      aws.String(c.userPoolID),
			PaginationToken: paginationToken,
		})
		if err != nil {
			return nil, fmt.Errorf("listing users: %w", err)
		}

		for _, u := range resp.Users {
			id, name, email, approved := parseUserAttributes(u.Attributes)
			username := aws.ToString(u.Username)
			// Prefer a human-readable label. Federated (Google) users have a
			// username like "google_<sub>", so fall back name -> email -> username.
			display := name
			if display == "" {
				display = email
			}
			if display == "" {
				display = username
			}
			users = append(users, User{
				ID:        id,
				Username:  username,
				Name:      display,
				Email:     email,
				Approved:  approved,
				CreatedAt: aws.ToTime(u.UserCreateDate),
			})
		}

		if resp.PaginationToken == nil {
			break
		}
		paginationToken = resp.PaginationToken
	}

	return users, nil
}

// parseUserAttributes extracts custom:Id, name, email and custom:Approved from
// Cognito attributes.
func parseUserAttributes(attributes []types.AttributeType) (id, name, email string, approved bool) {
	for _, att := range attributes {
		value := aws.ToString(att.Value)
		switch aws.ToString(att.Name) {
		case "custom:Id":
			id = value
		case "name":
			name = value
		case "email":
			email = value
		case "custom:Approved":
			approved = value == "true"
		}
	}
	return
}

// GetUser retrieves a user by ID, or nil if not found.
func (c *Client) GetUser(ctx context.Context, id string) (*User, error) {
	users, err := c.ListUsers(ctx)
	if err != nil {
		return nil, err
	}

	for _, u := range users {
		if u.ID == id {
			return &u, nil
		}
	}

	return nil, nil
}

// DeleteUser removes a user from Cognito by username.
func (c *Client) DeleteUser(ctx context.Context, username string) error {
	_, err := c.client.AdminDeleteUser(ctx, &cognitoidentityprovider.AdminDeleteUserInput{
		UserPoolId: aws.String(c.userPoolID),
		Username:   aws.String(username),
	})
	if err != nil {
		return fmt.Errorf("deleting user: %w", err)
	}
	return nil
}

// SetApproval updates the custom:Approved attribute for a user.
func (c *Client) SetApproval(ctx context.Context, username string, approved bool) error {
	value := "false"
	if approved {
		value = "true"
	}

	_, err := c.client.AdminUpdateUserAttributes(ctx, &cognitoidentityprovider.AdminUpdateUserAttributesInput{
		UserPoolId: aws.String(c.userPoolID),
		Username:   aws.String(username),
		UserAttributes: []types.AttributeType{
			{
				Name:  aws.String("custom:Approved"),
				Value: aws.String(value),
			},
		},
	})
	if err != nil {
		return fmt.Errorf("updating user approval: %w", err)
	}
	return nil
}
