// Generated by Claude.
// Cognito client for direct AWS SDK access to user management operations.
// Uses IAM credentials (env vars, AWS profile, or instance role) instead of Cognito user auth.
package cognito

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
)

type User struct {
	ID        string
	Name      string
	Role      string
	CreatedAt time.Time
}

type Client struct {
	client     *cognitoidentityprovider.Client
	userPoolID string
}

// NewClient creates a Cognito client configured with AWS credentials from the environment.
func NewClient(ctx context.Context, region, userPoolID string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}

	return &Client{
		client:     cognitoidentityprovider.NewFromConfig(cfg),
		userPoolID: userPoolID,
	}, nil
}

// ListUsers retrieves all users from the Cognito user pool with pagination.
func (c *Client) ListUsers(ctx context.Context) ([]User, error) {
	var users []User
	var paginationToken *string

	for {
		resp, err := c.client.ListUsers(ctx, &cognitoidentityprovider.ListUsersInput{
			UserPoolId:      aws.String(c.userPoolID),
			PaginationToken: paginationToken,
		})
		if err != nil {
			return nil, fmt.Errorf("listing users: %w", err)
		}

		for _, u := range resp.Users {
			id, role := parseUserAttributes(u.Attributes)
			users = append(users, User{
				ID:        id,
				Name:      aws.ToString(u.Username),
				Role:      role,
				CreatedAt: aws.ToTime(u.UserCreateDate),
			})
		}

		if resp.PaginationToken == nil {
			break
		}
		paginationToken = resp.PaginationToken
	}

	return users, nil
}

// parseUserAttributes extracts the normalized user ID and role from Cognito attributes.
func parseUserAttributes(attributes []types.AttributeType) (id, role string) {
	for _, att := range attributes {
		switch aws.ToString(att.Name) {
		case "sub":
			id = normalizeID(aws.ToString(att.Value))
		case "custom:Role":
			role = aws.ToString(att.Value)
		}
	}
	return id, role
}

// normalizeID converts a UUID to the application format (uppercase, no dashes).
func normalizeID(val string) string {
	return strings.ToUpper(strings.ReplaceAll(val, "-", ""))
}

// GetUser retrieves a user by ID, or nil if not found.
func (c *Client) GetUser(ctx context.Context, id string) (*User, error) {
	users, err := c.ListUsers(ctx)
	if err != nil {
		return nil, err
	}

	for _, u := range users {
		if u.ID == id {
			return &u, nil
		}
	}

	return nil, nil
}

// DeleteUser removes a user from Cognito by username.
func (c *Client) DeleteUser(ctx context.Context, username string) error {
	_, err := c.client.AdminDeleteUser(ctx, &cognitoidentityprovider.AdminDeleteUserInput{
		UserPoolId: aws.String(c.userPoolID),
		Username:   aws.String(username),
	})
	if err != nil {
		return fmt.Errorf("deleting user: %w", err)
	}
	return nil
}
