// Generated by Claude.
// Warm Bistro themed splash screen shown during app initialization
import { Box, Typography, alpha } from '@mui/material';
import RestaurantIcon from '@mui/icons-material/Restaurant';

const SplashScreen = () => {
  return (
    <Box
      sx={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: (theme) =>
          theme.palette.mode === 'dark'
            ? `linear-gradient(135deg, #1A1612 0%, #2A2420 100%)`
            : `linear-gradient(135deg, #FFF8F0 0%, #F5EBE0 100%)`,
        zIndex: 9999,
      }}
    >
      {/* Decorative background elements */}
      <Box
        sx={{
          position: 'absolute',
          top: '10%',
          right: '5%',
          width: '40%',
          height: '40%',
          background: (theme) =>
            `radial-gradient(circle, ${alpha(theme.palette.primary.main, 0.08)} 0%, transparent 70%)`,
          borderRadius: '50%',
          filter: 'blur(60px)',
          pointerEvents: 'none',
        }}
      />
      <Box
        sx={{
          position: 'absolute',
          bottom: '10%',
          left: '5%',
          width: '50%',
          height: '40%',
          background: (theme) =>
            `radial-gradient(circle, ${alpha(theme.palette.secondary.main, 0.1)} 0%, transparent 70%)`,
          borderRadius: '50%',
          filter: 'blur(60px)',
          pointerEvents: 'none',
        }}
      />

      {/* Logo */}
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 100,
          height: 100,
          borderRadius: '50%',
          background: (theme) =>
            `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.primary.dark} 100%)`,
          boxShadow: (theme) =>
            `0 12px 40px ${alpha(theme.palette.primary.main, 0.4)}`,
          mb: 3,
          animation: 'pulse 2s ease-in-out infinite',
          '@keyframes pulse': {
            '0%, 100%': {
              transform: 'scale(1)',
              boxShadow: (theme) =>
                `0 12px 40px ${alpha(theme.palette.primary.main, 0.4)}`,
            },
            '50%': {
              transform: 'scale(1.05)',
              boxShadow: (theme) =>
                `0 16px 50px ${alpha(theme.palette.primary.main, 0.5)}`,
            },
          },
        }}
      >
        <RestaurantIcon sx={{ fontSize: 50, color: '#FFF8F0' }} />
      </Box>

      {/* App name */}
      <Typography
        variant="h4"
        sx={{
          fontFamily: '"Playfair Display", Georgia, serif',
          fontWeight: 600,
          color: 'text.primary',
          letterSpacing: '-0.02em',
          mb: 1,
        }}
      >
        Meal Planner
      </Typography>

      {/* Tagline */}
      <Typography
        variant="body2"
        sx={{
          color: 'text.secondary',
          mb: 4,
        }}
      >
        Plan together, dine together
      </Typography>

      {/* Loading indicator */}
      <Box
        sx={{
          display: 'flex',
          gap: 1,
        }}
      >
        {[0, 1, 2].map((i) => (
          <Box
            key={i}
            sx={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              backgroundColor: 'primary.main',
              animation: 'bounce 1.4s ease-in-out infinite',
              animationDelay: `${i * 0.16}s`,
              '@keyframes bounce': {
                '0%, 80%, 100%': {
                  transform: 'scale(0.6)',
                  opacity: 0.4,
                },
                '40%': {
                  transform: 'scale(1)',
                  opacity: 1,
                },
              },
            }}
          />
        ))}
      </Box>
    </Box>
  );
};

export default SplashScreen;
