// Generated by Claude.
import { useRegisterSW } from 'virtual:pwa-register/react';
import { Snackbar, Box } from '@mui/material';
import SystemUpdateIcon from '@mui/icons-material/SystemUpdate';

/**
 * PWA update prompt - shows a clickable banner when a new version is available.
 * Clicking anywhere on the banner triggers the update and page reload.
 */
const UpdatePrompt = () => {
  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW();

  const handleUpdate = () => {
    updateServiceWorker(true);
  };

  return (
    <Snackbar
      open={needRefresh}
      anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      sx={{ bottom: { xs: 70, sm: 24 } }} // Above bottom nav on mobile
    >
      <Box
        onClick={handleUpdate}
        sx={{
          display: 'flex',
          alignItems: 'center',
          gap: 1,
          px: 2,
          py: 1.5,
          bgcolor: 'primary.main',
          color: 'primary.contrastText',
          borderRadius: 1,
          cursor: 'pointer',
          boxShadow: 3,
          '&:hover': {
            bgcolor: 'primary.dark',
          },
          '&:active': {
            transform: 'scale(0.98)',
          },
        }}
      >
        <SystemUpdateIcon />
        <span>Update available - tap to refresh</span>
      </Box>
    </Snackbar>
  );
};

export default UpdatePrompt;
