// Generated by Claude.
package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	ddbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/spf13/cobra"

	"isnan.eu/meal-planner/cli/internal/config"
	"isnan.eu/meal-planner/cli/internal/dynamodb"
)

var groupForceDelete bool
var groupDryRun bool

var groupsCmd = &cobra.Command{
	Use:   "groups",
	Short: "Manage groups",
}

var groupsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all groups",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}

		ctx := context.Background()
		client, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}

		items, err := client.ScanGroups(ctx)
		if err != nil {
			return fmt.Errorf("listing groups: %w", err)
		}

		if len(items) == 0 {
			fmt.Println("No groups found.")
			return nil
		}

		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "ID\tNAME\tCREATED AT")
		for _, item := range items {
			id := strings.TrimPrefix(item.PK, "group#")
			name := getGroupStringAttr(item.Attributes, "GroupName")
			createdAt := getGroupStringAttr(item.Attributes, "CreatedAt")
			fmt.Fprintf(w, "%s\t%s\t%s\n", id, name, createdAt)
		}
		w.Flush()

		return nil
	},
}

var groupsInspectCmd = &cobra.Command{
	Use:   "inspect <group-id>",
	Short: "Show members and schedules of a group",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		groupID := args[0]

		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}

		ctx := context.Background()
		client, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}

		// First, get the group to verify it exists and get its name
		groupPK := "group#" + groupID
		groupItems, err := client.QueryByPK(ctx, groupPK)
		if err != nil {
			return fmt.Errorf("querying group: %w", err)
		}
		if len(groupItems) == 0 {
			return fmt.Errorf("unknown group: %s", groupID)
		}

		groupName := getGroupStringAttr(groupItems[0].Attributes, "GroupName")
		gsi1pk := "group#" + groupID

		// Query GSI1 for members
		members, err := client.QueryByGSI1(ctx, gsi1pk, "member#")
		if err != nil {
			return fmt.Errorf("querying group members: %w", err)
		}

		// Query GSI1 for schedules (includes default and weekly)
		schedules, err := client.QueryByGSI1(ctx, gsi1pk, "schedule#")
		if err != nil {
			return fmt.Errorf("querying group schedules: %w", err)
		}

		// Separate default and weekly schedules
		var defaultSchedules, weeklySchedules []dynamodb.Item
		for _, s := range schedules {
			gsi1sk := getGroupStringAttr(s.Attributes, "GSI1SK")
			if strings.HasPrefix(gsi1sk, "schedule#default") {
				defaultSchedules = append(defaultSchedules, s)
			} else {
				weeklySchedules = append(weeklySchedules, s)
			}
		}

		fmt.Printf("Group: %s (%s)\n", groupName, groupID)
		fmt.Printf("Members: %d\n", len(members))
		fmt.Printf("Default Schedules: %d\n", len(defaultSchedules))
		fmt.Printf("Weekly Schedules: %d\n", len(weeklySchedules))

		// Display members
		if len(members) > 0 {
			fmt.Println("\nMembers:")
			w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
			fmt.Fprintln(w, "  MEMBER ID\tNAME\tROLE")
			for _, item := range members {
				memberID := getGroupStringAttr(item.Attributes, "MemberId")
				memberName := getGroupStringAttr(item.Attributes, "MemberName")
				role := getGroupStringAttr(item.Attributes, "Role")
				fmt.Fprintf(w, "  %s\t%s\t%s\n", memberID, memberName, role)
			}
			w.Flush()
		}

		// Display weekly schedules
		if len(weeklySchedules) > 0 {
			fmt.Println("\nWeekly Schedules:")
			w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
			fmt.Fprintln(w, "  MEMBER\tWEEK")
			for _, item := range weeklySchedules {
				memberName := getGroupStringAttr(item.Attributes, "MemberName")
				year := getGroupNumAttr(item.Attributes, "Year")
				week := getGroupNumAttr(item.Attributes, "WeekNumber")
				fmt.Fprintf(w, "  %s\t%s-%s\n", memberName, year, week)
			}
			w.Flush()
		}

		return nil
	},
}

var groupsDeleteCmd = &cobra.Command{
	Use:   "delete <group-id>",
	Short: "Delete a group and all associated data",
	Long:  "Deletes the group and all associated data (memberships, schedules, comments, notices).",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		groupID := args[0]

		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}

		ctx := context.Background()
		client, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}

		// Get the group record
		groupPK := "group#" + groupID
		groupItems, err := client.QueryByPK(ctx, groupPK)
		if err != nil {
			return fmt.Errorf("querying group: %w", err)
		}
		if len(groupItems) == 0 {
			return fmt.Errorf("unknown group: %s", groupID)
		}

		groupName := getGroupStringAttr(groupItems[0].Attributes, "GroupName")

		// Query GSI1 for all items related to this group (no prefix = all)
		gsi1pk := "group#" + groupID
		gsi1Items, err := client.QueryByGSI1(ctx, gsi1pk, "")
		if err != nil {
			return fmt.Errorf("querying group items: %w", err)
		}

		// Count by entity type
		entityCounts := make(map[string]int)
		entityCounts["Group"] = 1 // The group record itself
		for _, item := range gsi1Items {
			entityType := groupEntityTypeFromGSI1SK(item)
			entityCounts[entityType]++
		}

		// Total items = group record + GSI1 items
		totalItems := 1 + len(gsi1Items)

		// Show what will be deleted
		if groupDryRun {
			fmt.Println("[DRY RUN] The following would be deleted:")
			fmt.Println()
		}

		fmt.Printf("Group: %s (%s)\n", groupName, groupID)
		fmt.Printf("Items to delete: %d\n", totalItems)
		for entityType, count := range entityCounts {
			fmt.Printf("  - %s: %d\n", entityType, count)
		}

		// In dry-run mode, show detailed items
		if groupDryRun {
			fmt.Println("\nDetails:")
			fmt.Printf("  [Group] %s\n", groupName)
			for _, item := range gsi1Items {
				fmt.Printf("  %s\n", formatGroupItemDetail(item))
			}
			fmt.Println("\n[DRY RUN] No changes made.")
			return nil
		}

		if !groupForceDelete {
			fmt.Print("\nAre you sure you want to delete this group? [y/N]: ")
			reader := bufio.NewReader(os.Stdin)
			response, _ := reader.ReadString('\n')
			response = strings.TrimSpace(strings.ToLower(response))
			if response != "y" && response != "yes" {
				fmt.Println("Aborted.")
				return nil
			}
		}

		// Delete GSI1 items first
		if len(gsi1Items) > 0 {
			fmt.Printf("Deleting %d related items...\n", len(gsi1Items))
			if err := client.DeleteItems(ctx, gsi1Items); err != nil {
				return fmt.Errorf("deleting related items: %w", err)
			}
		}

		// Delete the group record
		fmt.Println("Deleting group record...")
		if err := client.DeleteItems(ctx, groupItems); err != nil {
			return fmt.Errorf("deleting group record: %w", err)
		}

		fmt.Printf("\nGroup %s successfully deleted.\n", groupName)
		return nil
	},
}

// groupEntityTypeFromGSI1SK infers entity type from GSI1SK attribute.
func groupEntityTypeFromGSI1SK(item dynamodb.Item) string {
	gsi1sk := getGroupStringAttr(item.Attributes, "GSI1SK")
	switch {
	case strings.HasPrefix(gsi1sk, "member#"):
		return "Membership"
	case strings.HasPrefix(gsi1sk, "schedule#default"):
		return "Default Schedule"
	case strings.HasPrefix(gsi1sk, "schedule#"):
		return "Schedule"
	case strings.HasPrefix(gsi1sk, "comments#"):
		return "Comments"
	case strings.HasPrefix(gsi1sk, "notice#"):
		return "Notice"
	default:
		return "Unknown"
	}
}

// formatGroupItemDetail returns a human-readable description of a group-related item.
func formatGroupItemDetail(item dynamodb.Item) string {
	entityType := groupEntityTypeFromGSI1SK(item)
	memberName := getGroupStringAttr(item.Attributes, "MemberName")
	year := getGroupNumAttr(item.Attributes, "Year")
	week := getGroupNumAttr(item.Attributes, "WeekNumber")

	switch entityType {
	case "Membership":
		memberID := getGroupStringAttr(item.Attributes, "MemberId")
		return fmt.Sprintf("[%s] %s (%s)", entityType, memberName, memberID)
	case "Default Schedule":
		return fmt.Sprintf("[%s] %s", entityType, memberName)
	case "Schedule":
		return fmt.Sprintf("[%s] %s (week %s-%s)", entityType, memberName, year, week)
	case "Comments":
		return fmt.Sprintf("[%s] %s (week %s-%s)", entityType, memberName, year, week)
	case "Notice":
		return fmt.Sprintf("[%s] %s (week %s-%s)", entityType, memberName, year, week)
	default:
		return fmt.Sprintf("[%s] %s", entityType, item.SK)
	}
}

// getGroupStringAttr extracts a string attribute value from DynamoDB item.
func getGroupStringAttr(attrs map[string]ddbtypes.AttributeValue, key string) string {
	if v, ok := attrs[key].(*ddbtypes.AttributeValueMemberS); ok {
		return v.Value
	}
	return ""
}

// getGroupNumAttr extracts a number attribute value as string from DynamoDB item.
func getGroupNumAttr(attrs map[string]ddbtypes.AttributeValue, key string) string {
	if v, ok := attrs[key].(*ddbtypes.AttributeValueMemberN); ok {
		return v.Value
	}
	return ""
}

func init() {
	groupsDeleteCmd.Flags().BoolVarP(&groupForceDelete, "force", "f", false, "skip confirmation prompt")
	groupsDeleteCmd.Flags().BoolVar(&groupDryRun, "dry-run", false, "show what would be deleted without making changes")

	groupsCmd.AddCommand(groupsListCmd)
	groupsCmd.AddCommand(groupsInspectCmd)
	groupsCmd.AddCommand(groupsDeleteCmd)
	rootCmd.AddCommand(groupsCmd)
}
