// Generated by Claude.
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var (
	cfgFile  string
	username string
	password string
)

var rootCmd = &cobra.Command{
	Use:   "meal-planner-cli",
	Short: "Meal Planner admin CLI tool",
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		if username == "" {
			username = os.Getenv("MPCLI_USERNAME")
		}
		if password == "" {
			password = os.Getenv("MPCLI_PASSWORD")
		}
		if username == "" {
			return fmt.Errorf("username is required (--username flag or MPCLI_USERNAME env var)")
		}
		if password == "" {
			return fmt.Errorf("password is required (--password flag or MPCLI_PASSWORD env var)")
		}
		return nil
	},
}

func init() {
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "./config.json", "path to config file")
	rootCmd.PersistentFlags().StringVar(&username, "username", "", "Cognito username (env: MPCLI_USERNAME)")
	rootCmd.PersistentFlags().StringVar(&password, "password", "", "Cognito password (env: MPCLI_PASSWORD)")
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
