// Generated by Claude.
package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var cfgFile string

var rootCmd = &cobra.Command{
	Use:   "meal-planner-cli",
	Short: "Meal Planner admin CLI tool",
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		// If no config specified, default to config.json next to the binary
		if cfgFile == "" {
			exe, err := os.Executable()
			if err != nil {
				return fmt.Errorf("resolving executable path: %w", err)
			}
			cfgFile = filepath.Join(filepath.Dir(exe), "config.json")
		}
		return nil
	},
}

func init() {
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "path to config file (default: config.json next to binary)")
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
