// Generated by Claude.
package cmd

import (
	"context"
	"fmt"
	"os"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"isnan.eu/meal-planner/cli/internal/api"
	"isnan.eu/meal-planner/cli/internal/auth"
	"isnan.eu/meal-planner/cli/internal/config"
)

var usersCmd = &cobra.Command{
	Use:   "users",
	Short: "Manage users",
}

var usersListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all users",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}

		ctx := context.Background()
		token, err := auth.Authenticate(ctx, cfg.Region, cfg.UserPoolID, cfg.ClientID, username, password)
		if err != nil {
			return fmt.Errorf("authenticating: %w", err)
		}

		client := api.NewClient(cfg.URL, token)
		users, err := client.ListUsers()
		if err != nil {
			return fmt.Errorf("listing users: %w", err)
		}

		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "ID\tNAME\tROLE\tCREATED AT")
		for _, u := range users {
			fmt.Fprintf(w, "%s\t%s\t%s\t%s\n", u.ID, u.Name, u.Role, u.CreatedAt)
		}
		w.Flush()

		return nil
	},
}

func init() {
	usersCmd.AddCommand(usersListCmd)
	rootCmd.AddCommand(usersCmd)
}
