const FETCHING_TOKEN = 'FETCHING_TOKEN';
const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
const SIGNING_IN = 'SIGNING_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

const FETCHING_SCHEDULES = 'FETCHING_SCHEDULES';
const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';
const FETCH_SCHEDULES_ERROR = 'FETCH_SCHEDULES_ERROR';

const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

const SAVING_PERSONAL_SCHEDULE = 'SAVING_PERSONAL_SCHEDULE';
const SAVE_PERSONAL_SCHEDULE_SUCCESS = 'SAVE_PERSONAL_SCHEDULE_SUCCESS';
const SAVE_PERSONAL_SCHEDULE_ERROR = 'SAVE_PERSONAL_SCHEDULE_ERROR';

const SAVING_COMMENTS = 'SAVING_COMMENTS';
const SAVE_COMMENTS_SUCCESS = 'SAVE_COMMENTS_SUCCESS';
const SAVE_COMMENTS_ERROR = 'SAVE_COMMENTS_ERROR';

const SAVING_DEFAULT_SCHEDULE = 'SAVING_DEFAULT_SCHEDULE';
const SAVE_DEFAULT_SCHEDULE_SUCCESS = 'SAVE_DEFAULT_SCHEDULE_SUCCESS';
const SAVE_DEFAULT_SCHEDULE_ERROR = 'SAVE_DEFAULT_SCHEDULE_ERROR';

const REFRESH_MEMBERS_SCHEDULES_SUCCESS = 'REFRESH_MEMBERS_SCHEDULES_SUCCES';
const REFRESH_MEMBERS_SCHEDULES_ERROR = 'REFRESH_MEMBERS_SCHEDULES_ERROR';

const SIGNING_OUT = 'SIGNING_OUT';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

const CHANGING_PASSWORD = 'CHANGING_PASSWORD';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export default {
  FETCHING_TOKEN,
  FETCH_TOKEN_SUCCESS,
  FETCH_TOKEN_ERROR,
  SIGNING_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  FETCHING_SCHEDULES,
  FETCH_SCHEDULES_SUCCESS,
  FETCH_SCHEDULES_ERROR,
  DISMISS_NOTIFICATION,
  SAVING_PERSONAL_SCHEDULE,
  SAVE_PERSONAL_SCHEDULE_SUCCESS,
  SAVE_PERSONAL_SCHEDULE_ERROR,
  SAVING_DEFAULT_SCHEDULE,
  SAVE_DEFAULT_SCHEDULE_SUCCESS,
  SAVE_DEFAULT_SCHEDULE_ERROR,
  REFRESH_MEMBERS_SCHEDULES_SUCCESS,
  REFRESH_MEMBERS_SCHEDULES_ERROR,
  SIGNING_OUT,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  CHANGING_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
  SAVING_COMMENTS,
  SAVE_COMMENTS_SUCCESS,
  SAVE_COMMENTS_ERROR,
};
