// Generated by Claude.
// DynamoDB client for direct AWS SDK access to table operations.
package dynamodb

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// Item represents a raw DynamoDB item with PK/SK and all attributes.
type Item struct {
	PK         string
	SK         string
	Attributes map[string]types.AttributeValue
}

type Client struct {
	client    *dynamodb.Client
	tableName string
}

// NewClient creates a DynamoDB client configured with AWS credentials from the environment.
func NewClient(ctx context.Context, region, tableName string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}

	return &Client{
		client:    dynamodb.NewFromConfig(cfg),
		tableName: tableName,
	}, nil
}

// QueryByPK retrieves all items with the given partition key.
func (c *Client) QueryByPK(ctx context.Context, pk string) ([]Item, error) {
	var items []Item
	var lastKey map[string]types.AttributeValue

	for {
		input := &dynamodb.QueryInput{
			TableName:              aws.String(c.tableName),
			KeyConditionExpression: aws.String("#pk = :pk"),
			ExpressionAttributeNames: map[string]string{
				"#pk": "PK",
			},
			ExpressionAttributeValues: map[string]types.AttributeValue{
				":pk": &types.AttributeValueMemberS{Value: pk},
			},
			ExclusiveStartKey: lastKey,
		}

		resp, err := c.client.Query(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("querying DynamoDB: %w", err)
		}

		for _, item := range resp.Items {
			parsed := Item{Attributes: item}

			// Extract PK and SK for convenience
			if v, ok := item["PK"].(*types.AttributeValueMemberS); ok {
				parsed.PK = v.Value
			}
			if v, ok := item["SK"].(*types.AttributeValueMemberS); ok {
				parsed.SK = v.Value
			}

			items = append(items, parsed)
		}

		if resp.LastEvaluatedKey == nil {
			break
		}
		lastKey = resp.LastEvaluatedKey
	}

	return items, nil
}

// QueryByGSI1 retrieves items from GSI1 with the given partition key and optional SK prefix.
func (c *Client) QueryByGSI1(ctx context.Context, gsi1pk string, skPrefix string) ([]Item, error) {
	var items []Item
	var lastKey map[string]types.AttributeValue

	for {
		input := &dynamodb.QueryInput{
			TableName: aws.String(c.tableName),
			IndexName: aws.String("GSI1"),
			ExpressionAttributeValues: map[string]types.AttributeValue{
				":pk": &types.AttributeValueMemberS{Value: gsi1pk},
			},
			ExclusiveStartKey: lastKey,
		}

		if skPrefix != "" {
			input.KeyConditionExpression = aws.String("#gsi1pk = :pk AND begins_with(#gsi1sk, :skprefix)")
			input.ExpressionAttributeNames = map[string]string{
				"#gsi1pk": "GSI1PK",
				"#gsi1sk": "GSI1SK",
			}
			input.ExpressionAttributeValues[":skprefix"] = &types.AttributeValueMemberS{Value: skPrefix}
		} else {
			input.KeyConditionExpression = aws.String("#gsi1pk = :pk")
			input.ExpressionAttributeNames = map[string]string{
				"#gsi1pk": "GSI1PK",
			}
		}

		resp, err := c.client.Query(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("querying GSI1: %w", err)
		}

		for _, item := range resp.Items {
			parsed := Item{Attributes: item}

			if v, ok := item["PK"].(*types.AttributeValueMemberS); ok {
				parsed.PK = v.Value
			}
			if v, ok := item["SK"].(*types.AttributeValueMemberS); ok {
				parsed.SK = v.Value
			}

			items = append(items, parsed)
		}

		if resp.LastEvaluatedKey == nil {
			break
		}
		lastKey = resp.LastEvaluatedKey
	}

	return items, nil
}

// ScanGroups retrieves all group items from the table.
// Groups have PK = SK = "group#<id>".
func (c *Client) ScanGroups(ctx context.Context) ([]Item, error) {
	var items []Item
	var lastKey map[string]types.AttributeValue

	for {
		input := &dynamodb.ScanInput{
			TableName:        aws.String(c.tableName),
			FilterExpression: aws.String("begins_with(#pk, :prefix) AND #pk = #sk"),
			ExpressionAttributeNames: map[string]string{
				"#pk": "PK",
				"#sk": "SK",
			},
			ExpressionAttributeValues: map[string]types.AttributeValue{
				":prefix": &types.AttributeValueMemberS{Value: "group#"},
			},
			ExclusiveStartKey: lastKey,
		}

		resp, err := c.client.Scan(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("scanning groups: %w", err)
		}

		for _, item := range resp.Items {
			parsed := Item{Attributes: item}

			if v, ok := item["PK"].(*types.AttributeValueMemberS); ok {
				parsed.PK = v.Value
			}
			if v, ok := item["SK"].(*types.AttributeValueMemberS); ok {
				parsed.SK = v.Value
			}

			items = append(items, parsed)
		}

		if resp.LastEvaluatedKey == nil {
			break
		}
		lastKey = resp.LastEvaluatedKey
	}

	return items, nil
}

// DeleteItems deletes multiple items by PK/SK pairs using BatchWriteItem.
// Handles batching (max 25 items per request) automatically.
func (c *Client) DeleteItems(ctx context.Context, items []Item) error {
	if len(items) == 0 {
		return nil
	}

	// BatchWriteItem supports max 25 items per request
	const batchSize = 25

	for i := 0; i < len(items); i += batchSize {
		end := i + batchSize
		if end > len(items) {
			end = len(items)
		}
		batch := items[i:end]

		var writeRequests []types.WriteRequest
		for _, item := range batch {
			writeRequests = append(writeRequests, types.WriteRequest{
				DeleteRequest: &types.DeleteRequest{
					Key: map[string]types.AttributeValue{
						"PK": &types.AttributeValueMemberS{Value: item.PK},
						"SK": &types.AttributeValueMemberS{Value: item.SK},
					},
				},
			})
		}

		input := &dynamodb.BatchWriteItemInput{
			RequestItems: map[string][]types.WriteRequest{
				c.tableName: writeRequests,
			},
		}

		// Handle unprocessed items with retry
		for {
			resp, err := c.client.BatchWriteItem(ctx, input)
			if err != nil {
				return fmt.Errorf("batch deleting items: %w", err)
			}

			// Check for unprocessed items
			if len(resp.UnprocessedItems) == 0 {
				break
			}
			input.RequestItems = resp.UnprocessedItems
		}
	}

	return nil
}
