// Generated by Claude.
package config

import (
	"encoding/json"
	"fmt"
	"os"
)

type Config struct {
	UserPoolID string `json:"userPoolId"`
	Region     string `json:"region"`
	TableName  string `json:"tableName"`
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config file: %w", err)
	}

	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config file: %w", err)
	}

	return &cfg, nil
}
