// Generated by Claude.
package api

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	Role      string `json:"role"`
}

type ListUsersResponse struct {
	Users []User `json:"users"`
}
